## Jesusfuck, a GIG for python:3? How about FUCK NO.
FROM alpine:3.21 AS installation

WORKDIR /usr/src/app

COPY . ./
RUN apk update; apk upgrade && \
    apk add python3 && \
    python3 -m venv ./venv && \
    ./venv/bin/pip install --no-cache-dir -r requirements.txt

FROM alpine:3.21
RUN apk update && apk upgrade && apk add python3
COPY --from=installation /usr/src/app /scrape

CMD [ "/scrape/venv/bin/python", "/scrape/scrape.py" ]
